---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
      - VERSION=docker
    volumes:
      - /mnt/plex/config:/config
      - /mnt/plex/tvseries:/tv
      - /mnt/plex/movies:/movies
    restart: unless-stopped